[package]
name = "set-builder"
version = "0.8.0-alpha.1"
edition = "2021"

[workspace]

[dependencies]
risc0-aggregation = { version = "0.5.0-alpha.1", path = "../..", default-features = false }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "main", default-features = false, features = ["std"] }
