[package]
name = "set-builder"
version = "0.5.0-alpha.1"
edition = "2021"

[workspace]

[dependencies]
risc0-aggregation = { version = "0.5.0-alpha.1", path = "../..", default-features = false }
risc0-zkvm = { version = "2.0.0", features = ["std"] }
