[package]
name = "token-stats-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { workspace = true, features = ["unstable"] }

[package.metadata.risc0]
methods = ["guest"]
